from __future__ import annotations
from typing import Protocol, Sequence, Any
from .models import Bar, BarSeries, Order, Fill, BacktestResumeState

class DataProvider(Protocol):
    def get_bars(self, symbol:str, timeframe:str, start_time:int, end_time:int) -> Sequence[Bar] | BarSeries: ...
    def get_lower_tf_bars(self, symbol:str, parent_timeframe:str, lower_timeframe:str, parent_bar:Bar) -> Sequence[Bar] | BarSeries: ...
class PineRuntime(Protocol):
    def begin_bar(self, bar:Bar, bar_index:int) -> None: ...
    def end_bar(self) -> None: ...
class GeneratedStrategy(Protocol):
    ctx: object
    def _process_bar(self, bar:Bar, bar_index:int) -> None: ...
class ResultWriter(Protocol):
    def write(self, result: object, path: str) -> None: ...
class BrokerAdapter(Protocol):
    def on_order(self, order:Order) -> None: ...
    def on_fill(self, fill:Fill) -> None: ...
class SerializableRuntime(Protocol):
    def export_state(self) -> object: ...
    def restore_state(self, state: object) -> None: ...
class SerializableStrategy(Protocol):
    def export_state(self) -> object: ...
    def restore_state(self, state: object) -> None: ...
